### ISSUE TITLE
Edit Chat title and members

### ISSUE THREAD

**Issue by Pasley70** [juho-jaakkola/elgg-chat#3] opened 2015-02-18 09:42 UTC
Would it be possble to edit the chat title easier (eg. changing the title without adding or deleting members) and could the members management more convenient (eg. list of active participants with delete button)?

**Comment by juho-jaakkola** [comment] 2015-02-18 09:52
Is this perhaps a duplicate of #1 ?

**Comment by juho-jaakkola** [comment] 2015-02-18 09:58
I believe this has been fixed in master. I just haven't release 1.9.2 yet.

Could you test with latest master?

**Comment by Pasley70** [comment] 2015-02-18 17:51
Yes, sorry! I have worked with the wrong Version. Thanx for your hint. By the way: Very nice PlugIn!

**Closed** 2015-02-18 17:51 UTC

**Comment by juho-jaakkola** [comment] 2015-02-18 18:13
Thanks for reminding me that I still haven't released 1.9.2 to the community! :)
